config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
    resources :spots, only: [:index, :destroy]
  end

  # ユーザー用　(public名前空間にまとめる)
  scope module: :public do
    devise_for :users, controllers: {
      registrations: "public/registrations"
    }

    root to: 'users#mypage'
    get 'homes/about', to: 'homes#about', as: :about

    get 'users/mypage'
    resources :users
    resources :spots do
      resources :post_comments, only: [:create, :destroy]
    end
  end

  # ゲストユーザー用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # タグ用
  get 'tags/:id', to: 'public/tags#show', as: 'tag'
  resources :tags, only: [:show]

  # Map用
  resource :map, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  GUEST_USER_EMAIL = "guest@example.com"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :spots, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to admin_dashboards_path, notice: 'ユーザーを削除しました。'
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/mypage.html.erb
<h1><%= @user.name %>さんのマイページ</h1>

<div class="profile-icon">
  <% if current_user.avatar.attached? %>
    <%= image_tag @user.avatar.variant(resize_to_limit: [150, 150]), class: "rounded-circle" %>
  <% else %>
    <%= image_tag "いらすとや_no_image.jpg", size: "150x150", class: "rounded-circle" %>
  <% end %>
</div>

<%= link_to "プロフィール編集", edit_user_registration_path, class: "btn btn-warning" %>

<hr>

<h1>My投稿一覧</h1>
<% @spots.each do |spot| %>
  <div class="spot-card">
    <p><strong>タイトル:</strong> <%= spot.title %></p>
    <p><strong>説明:</strong> <%= spot.body %></p>
    <% if spot.image.attached? %>
      <%= image_tag spot.image.variant(resize_to_limit: [300, 300]) %>
    <% else %>
      <%= image_tag 'いらすとや_no_image.jpg', size: "300x300" %>
    <% end %>
    <div class="spot-image">
      <%= link_to '詳細を見る', spot_path(spot), class: 'btn btn-info' %>
    </div>
  </div>

  <hr>

<% end %>