config/routes.rb
Rails.application.routes.draw do

  # 管理者用
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
    resources :spots, only: [:index, :destroy]
  end

  # ユーザー用　(public名前空間にまとめる)
  scope module: :public do
    devise_for :users, controllers: {
      registrations: "public/registrations"
    }

    root to: 'users#mypage'
    get 'homes/about', to: 'homes#about', as: :about

    get 'users/mypage'
    resources :users
    resources :spots do
      resources :post_comments, only: [:create, :destroy]
    end
  end

  # ゲストユーザー用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # タグ用
  get 'tags/:id', to: 'public/tags#show', as: 'tag'
  resources :tags, only: [:show]

  # Map用
  resource :map, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :spot
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :post_comments, dependent: :destroy
  has_many :spot_tags, dependent: :destroy
  has_many :tags, through: :spot_tags

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

  validates :address, presence: true

  geocoded_by :address do |obj, results|
    if result = results.first
      obj.latitude = result.latitude
      obj.longitude = result.longitude
      if zip_data = result.address_components.find { |c| c['types'].include?('postal_code') }
        obj.zipcode = zip_data['long_name']
      end
    end
  end
  after_validation :geocode, if: :address_changed?

  def get_image
    if image.attached?
      image
    else
      'いらすとや_no_image.jpg'
    end
  end

  def save_tags(save_spot_tags)
    # 登録されているタグを取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    # 古いタグを取得（登録されているタグ - フォームから新規に送られてきたタグ）
    old_tags = current_tags - save_spot_tags

    # 新しいタグの取得（フォームから新規に送られてきたタグ - 登録されているタグ
    new_tags = save_spot_tags - current_tags

    # 古いタグを削除
    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    # 新しいタグがテーブルに存在しなければ新規登録（重複チェック付き）
    new_tags.each do |new_name|
      tag = Tag.find_or_create_by(name: new_name)
      self.tags << tag unless self.tags.include?(tag)
    end
  end
end

app/models/spot_tag.rb
class SpotTag < ApplicationRecord
  belongs_to :spot
  belongs_to :tag
  validates :spot_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence:true, length:{maximum:20}
  has_many :spot_tags, dependent: :destroy
  has_many :spots, through: :spot_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  GUEST_USER_EMAIL = "guest@example.com"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :spots, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @spots = Spot.includes(:user).order(created_at: :desc)
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to admin_spots_path, notice: "投稿を削除しました。"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top], unless: :admin_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar, :introduction])
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :destroy, :update]
  
  def new
    @spot = Spot.new
  end

  # 投稿データの保存
  def create
    @spot = Spot.new(spot_params)
    @spot.user_id = current_user.id # ユーザーと紐づける
    if @spot.save
      redirect_to spot_path(@spot), notice: '投稿が保存されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end


  def index
    @spots = Spot.order(created_at: :desc)
  end

  def show
    @spot = Spot.find(params[:id])
  end

  def edit
    @spot = Spot.find(params[:id])
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      redirect_to spot_path(@spot), notice: "更新しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy
    redirect_to root_path, notice: '削除しました'
  end


  private

  def spot_params
    params.require(:spot).permit(:title, :body, :image)
  end

  def set_spot
    @spot =Spot.find(params[:id])
  end

  def authorize_user!
    redirect_to spots_path, alert: "権限がありません" if @spot.user != current_user
  end
  

end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/spots_helper.rb
module Admin::SpotsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/spot_helper.rb
module SpotHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-messages">
    <h4><%= model.errors.count %>件のエラーがあります</h4>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - SpotReview</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  </head>

  <body class="d-flex flex-column vh-100">
  
    <header class="site-header">
      <div class="container text-center py-5">
        <h1><%= link_to "Spot Review", root_path %></h1>
      </div>
    </header>

    <hr>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>

      <nav class="navbar navbar-light container mt-3 mb-3">

        <!-- 検索欄 -->
        <% if user_signed_in? %>
          <%= form_with url: (params[:model] == "user" ? users_path : spots_path), method: :get, local: true do |f| %>
            <%= f.text_field :spot_name, placeholder: "タイトル・ユーザーを検索", value: params[:spot_name], style: "width: 250px;" %>
            <%= f.text_field :tag_name, placeholder: "タグ検索", value: params[:tag_name] %>
            <%= f.submit "検索" %><br>

            <%= f.select :model, options_for_select({"User" => "user", "Title" => "title"}, params[:model]) %>
            <%= f.select :method, options_for_select({"完全一致" => "perfect", "後方一致" => "backward", "部分一致" => "partial"}, params[:method]) %><br>
          <% end %>
        <% end %>

        <!-- 新規登録、ログイン -->
        <div class="auth-buttons ms-3 d-none d-sm-flex">
          <% unless user_signed_in? %>
            <%= link_to "新規登録", new_user_registration_path, class: "btn btn-primary btn-sm mr-3" %>
            <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "btn btn-success btn-sm" %>
          <% end %>
        </div>

        <div class="dropdown">
          <button class="btn btn-outline-secondary dropdown-toggle custom-toggler" type="button" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bars"></i>
          </button>
  
          <div class="dropdown-menu dropdown-menu-right custom-dropdown-menu shadow border-0" aria-labelledby="userMenu">
            <div class="dropdown-arrow"></div> <% if user_signed_in? %>
              <%= link_to root_path, class: "dropdown-item" do %>
                <i class="fas fa-user-circle"></i> Myページ
              <% end %>
              <%= link_to new_spot_path, class: "dropdown-item" do %>
                <i class="fas fa-plus-square"></i> 投稿フォーム
              <% end %>
              <%= link_to spots_path, class: "dropdown-item" do %>
                <i class="fas fa-images"></i> 投稿一覧
              <% end %>
              <%= link_to users_path, class: "dropdown-item" do %>
                <i class="fas fa-users"></i> ユーザーの一覧
              <% end %>
              <%= link_to about_path, class: "dropdown-item" do %>
                <i class="fas fa-info-circle"></i> アバウト
              <% end %>
              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item text-danger" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            <% else %>
              <%= link_to new_user_registration_path, class: "dropdown-item" do %>
                <i class="fas fa-user-plus"></i> 新規登録
              <% end %>
              <%= link_to new_user_session_path, class: "dropdown-item" do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
              <% end %>
              <%= link_to users_guest_sign_in_path, method: :post, class: "dropdown-item text-success font-weight-bold" do %>
                <i class="fas fa-running"></i> ゲストログイン
              <% end %>
              <%= link_to about_path, class: "dropdown-item" do %>
                <i class="fas fa-info-circle"></i> アバウト
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>

    <main class="flex-grow-1 mb-5">
      <%= yield %>
    </main>

    <footer>
      <div class="social">
        <a href="https://facebook.com" target="_blank">
          <i class="fab fa-facebook-square"></i>
        </a>

        <a href="https://twitter.com" target="_blank">
          <i class="fab fa-twitter-square"></i>
        </a>
       
        <a href="https://instagram.com" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
      <p class="footer-text">© 2025 SpotReview. All Rights Reserved.</p>
      <div>
        <%= button_to "退会する", user_registration_path,
          data: { confirm: "本当に削除しますか？" },
          method: :delete,
          class: "btn btn-danger" %>
      </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.jpostal@0.1.8/jquery.jpostal.js"></script>
    <script>
    document.addEventListener("submit", function(e) {
      const form = e.target;
      const model = form.querySelector("[name='model']").value;
      form.action = model === "user" ? "/users" : "/spots";
    });
    </script>
  </body>
</html>